//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.DLL.ModelConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralama
    {
        public int KiralamalarId { get; set; }
        public int AracId { get; set; }
        public int MusteriId { get; set; }
        public System.DateTime AlinisTarihi { get; set; }
        public System.DateTime IadeTarihi { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
        public bool IsActive { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
