//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.DLLModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokenCars
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public int CustomerId { get; set; }
        public string BrokenDescription { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> UpdatorId { get; set; }
        public string Description { get; set; }
        public string IsActive { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
