//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.DLLModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YasinRentACarEntities : DbContext
    {
        public YasinRentACarEntities()
            : base("name=YasinRentACarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrokenCars> BrokenCars { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employess> Employess { get; set; }
        public virtual DbSet<RentalCars> RentalCars { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Rules> Rules { get; set; }
    }
}
