//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.DLLModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules
    {
        public int Id { get; set; }
        public string RuleName { get; set; }
        public string RuleDescription { get; set; }
        public System.DateTime RuleDuration { get; set; }
        public string RulePrice { get; set; }
        public int RentalCarId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdatorId { get; set; }
        public string Description { get; set; }
        public string IsActive { get; set; }
    }
}
